### ISSUE TITLE
Error: `Failed to parse configuration file`

### ISSUE THREAD

**Issue by bubbletroubles** [lycheeverse/lychee#1306] opened 2023-11-23 01:51 UTC
## Issue: 

When running lychee 0.13 on Windows, it displays the error `[ERROR] Error while loading config file "lychee.toml": Failed to parse configuration file`

## Steps to reproduce

Place `lychee.exe` and `lychee.toml` in the same folder. Run

`lychee.exe -c lychee.toml`

## Error

```PowerShell
PS C:\repos\lychee> .\lychee.exe  -c lychee.toml .   
[ERROR] Error while loading config file "lychee.toml": Failed to parse configuration file
```

## Other information

I've downloaded the raw example config file from https://github.com/lycheeverse/lychee/blob/master/lychee.example.toml and renamed it to lychee.toml. The issue can be reproduced with this file.

The config file encoding is `UTF-8`

I've also tried a config file with only the content below (e.g. a one line file) and it gives the same error
`verbose = false`

The system is definately finding the file, as when I run lychee with an invalid config file name, the error is 
`[ERROR] Error while loading config file "lychee-invalid-file.toml": The system cannot find the file specified. (os error 2)`

**Comment by theapiarist** [comment] 2023-12-28 16:38
I think the parse error is that the cupplied configuration file is not in TOML format. Compare it to Cargo.toml.

I can get rid of the error by adding a section heading ... 

```
[display]
verbose = "debug"
```

but I still cannot get excludes or anything else to work. Lychee works perfectly from the command line but I ned to use it to run as a cron job from a config file.

Any chance of supplying a working example, with one or two simple switches to illustrate its use?
Happy New Year

**Comment by xrstf** [comment] 2024-01-04 13:42
I have the same issue. A single error message, but not telling me what the actual issue is. I ran my lychee.toml through a TOML validator and it's valid. Now I'm trying to bisect and commenting out individual config lines, to find what the actual root cause is. So far it seems `exclude_path` was renamed or removed at some point.

**Comment by mre** [comment] 2024-01-04 21:15
Sorry to hear that, folks.
I've added better error messages with https://github.com/lycheeverse/lychee/issues/1306.
We'll do a new release tomorrow, which will include this change.

**Comment by mre** [comment] 2024-01-04 21:26
@bubbletroubles, the example config in the repo only works for `master`. The reason is that the latest changes were not released yet, causing some churn. I just tested the example config with the latest unreleased version and it works. There is also an integration test, which makes sure it won't break. Please hold on until the new version is released.

@theapiarist, I can't see any issues with your config. It should work with the current and the next version. I tested on macOS and on Linux with the Docker container:

```sh
docker run -it -v $PWD:/config lycheeverse/lychee --config /config/lychee.toml --verbose --no-progress .
```

So it looks like it's an issue with the Raspberry Pi? 🤔 In any case, maybe you can try again tomorrow after the release.

@xrstf the `verbose` option was extended. Previously (probably in your current version) it was a boolean, but now it is a string. See https://github.com/lycheeverse/lychee/issues/970
This, too, should be resolved with the next release, but you can test right away by either changing it to a string or a bool, depending on your current config.

**Comment by mre** [comment] 2024-01-05 17:13
lychee version 0.14.0 finally got released. 🎉 
Thanks to this release, the issue should be resolved now.
Please reopen if this is not the case, and apologies for the long delay.

On top of that, the error message for TOML parsing errors is more extensive now, which should help with troubleshooting.
@theapiarist, this might help you troubleshoot the issues you experienced.

**Closed by mre** 2024-01-05 17:13 UTC

**Comment by theapiarist** [comment] 2024-01-05 22:31
Works well ... on Mac and RPi. No idea what the issue was before. With thanks.

**Comment by mre** [comment] 2024-01-05 23:05
Good news are always great to hear. 😆
