### ISSUE TITLE
Non-link footnotes in markdown are reported as broken links.

### ISSUE THREAD

**Issue by jan-ferdinand** [lycheeverse/lychee#1409] opened 2024-04-22 18:19 UTC
Consider the following file `/tmp/file.md`:

```md
Some[^1] text.

[^1]: short
```

Running `lychee .` produces the following error

```sh
[./file.md]:
✗ [ERR] file:///tmp/short | Failed: Cannot find file
```

To the best of my knowledge, `short` is never a link but always a footnote. It would be nice for these presumed false positives to not occur.

**Comment by jan-ferdinand** [comment] 2024-04-23 12:28
I've added a test in #1410. Unfortunately, I can't figure out where extraction of markdown links is happening.

**Comment by mre** [comment] 2024-04-26 10:06
Thanks. :)

**Comment by jan-ferdinand** [comment] 2024-04-26 14:29
You're more than welcome. :blush: I'd have liked to give resolution a shot, but couldn't identify where to start. It's probably somewhere in the parser? If so, that's probably more than I can chew right now.

**Comment by mre** [comment] 2024-04-26 18:19
Feel free to dive in. But yeah, it's in the markdown parser in pulldown_cmark, which is the crate we're using for it.

**Comment by thomas-zahner** [comment] 2024-06-14 10:24
I had a closer look at this. Actually this is not a bug in lychee.
We use `pulldown_cmark` to parse Markdown thus we are treating all Markdown as CommonMark. CommonMark does not know specify footnotes, so there really are no footnotes. Instead, there are [shortcut reference links](https://spec.commonmark.org/0.31.2/#shortcut-reference-link) and the "footnote" in your example is treated as a shortcut reference links.

So the example you provide:

```
Some[^1] text.

[^1]: short
```

[is understood](https://spec.commonmark.org/dingus/?text=Some%5B%5E1%5D%20text.%0A%0A%5B%5E1%5D%3A%20short) as shortcut reference link and therefore converted into the following HTML:

```
<p>Some<a href="short">^1</a> text.</p>
```

When not using a valid (relative) link the text is simply understood as normal paragraphs:

```
Some[^1] text.

[^1]: multiple words
```

[now becomes](https://spec.commonmark.org/dingus/?text=Some%5B%5E1%5D%20text.%0A%0A%5B%5E1%5D%3A%20multiple%20words):

```
<p>Some[^1] text.</p>
<p>[^1]: multiple words</p>
```

So footnotes are neither part of CommonMark nor GitHub Flavored Markdown (the only Markdown specifications I know of) but still some people might be using them because many non-specified flavours do make use of them. (the beauty of the [Markdown flavour swamp](https://github.com/commonmark/commonmark-spec/wiki/markdown-flavors))

So one thing we could do is to treat the link of these shortcut type links not as URL but as plain text (`extract_plaintext`) where we extract the URLs from. This would reduce the false positive rate when people are checking Markdown which is not CommonMark compliant, which is probably the big majority. @mre what do you think?

**Comment by jan-ferdinand** [comment] 2024-06-14 10:47
Interesting! Thanks for digging and explaining what's going on.

> footnotes are [not part of] GitHub Flavored Markdown […]

[I disagree](https://docs.github.com/en/get-started/writing-on-github/getting-started-with-writing-and-formatting-on-github/basic-writing-and-formatting-syntax#footnotes). :relieved:

**Comment by thomas-zahner** [comment] 2024-06-14 10:58
No problem :+1: 

> I disagree 😌

Wait...
I stated that because I could not find anything related to footnotes in their [official spec](https://github.github.com/gfm/#links) but in the documentation link you sent they go on explaining how to use footnotes. So I guess that they are not even adhering to their own spec or are referencing some other falvour there? :exploding_head:

**Comment by jan-ferdinand** [comment] 2024-06-14 11:38
The markdown swamp gets swampier the further you go. :cloud_with_rain: The strongest indication of them going against their own spec that I can see is: this[^1] works.

[^1]: thing

**Comment by mre** [comment] 2024-08-06 15:41
The linked PR has a proposed solution now. @jan-ferdinand fyi.

**Comment by mre** [comment] 2024-08-11 10:53
This is now fixed in `master` and will be released with the next version.
Thanks @jan-ferdinand for the test and for opening the issue.

**Closed by mre** 2024-08-11 10:53 UTC
Labels: bug
