### ISSUE TITLE
Raw output option

### ISSUE THREAD

**Issue by T145** [lycheeverse/lychee#271] opened 2021-06-25 18:07 UTC
Instead of #268, have a raw option to generate output that doesn't include emoji and the process indicator. This will help the results be piped into other programs like `jq` that people can then use to transform into JSON on their own. It could look like:
```
./lychee README.md --raw -v
```

**Comment by lebensterben** [comment] 2021-06-25 18:22
This is a good point.
Rust programmers are used to UTF compatibility but in reality other components in the toolchain may not be UTF compatible.

Meanwhile, if you can tell lychee to output results in JSON format. That's friendlier for jq.

**Comment by mre** [comment] 2022-04-25 17:23
Gonna close this as resolved. Feel free to reopen if it doesn't work as expected.

**Comment by alexanderbazhenoff** [comment] 2024-03-29 23:42
Just wanna know how to enable colors in GitLab CI console? No info in README.

**Comment by mre** [comment] 2024-04-03 17:52
Sorry for the late reply.
You can try to set the `NO_COLOR=1` environment variable, so

```sh
export NO_COLOR=1
lychee ...
```

or 

```sh
NO_COLOR=1 lychee ...
```

**Comment by alexanderbazhenoff** [comment] 2024-04-03 19:24
> Sorry for the late reply. You can try to set the `NO_COLOR=1` environment variable, so

No problem, but I meant enable colors :) Anyway neither `NO_COLOR=0` (and `NO_COLOR=false`), nor `NO_COLOR=1` (and `NO_COLOR=true`) got color changes in my GitLab CI, it's stll b/w. Using [lychee-v0.14.3-aarch64-unknown-linux-gnu.tar.gz](https://github.com/lycheeverse/lychee/releases/download/v0.14.3/lychee-v0.14.3-aarch64-unknown-linux-gnu.tar.gz):

```
  script:
    - NO_COLOR=0 lychee -n .
```

![lychee_bw](https://github.com/lycheeverse/lychee/assets/19375799/6cf9eb91-6043-4d1a-8f83-6be9ae90e80f)

Any ideas?

**Comment by mre** [comment] 2024-04-04 10:07
@alexanderbazhenoff, I took a stab at it here: https://github.com/lycheeverse/lychee/pull/1398
If you want, you can try it out by installing the version from that branch. I'd appreciate some feedback.

**Comment by alexanderbazhenoff** [comment] 2024-04-10 00:46
> @alexanderbazhenoff, I took a stab at it here: #1398 If you want, you can try it out by installing the version from that branch. I'd appreciate some feedback.

Sorry for long reply. I have placed a new binary alongside with an old, but named them as `lychee2`. So, `-n --mode emoji` worked as described behind, defaults still no color:

![lychee-new](https://github.com/lycheeverse/lychee/assets/19375799/c3aa4975-b685-4b8b-a473-f89fb92357c0)
Runing the same defaults locally via console command is nice and colored:

![lychee-local](https://github.com/lycheeverse/lychee/assets/19375799/a6ed3ffb-471d-478e-a1d4-9262b53d1102)


No additional env variables set like COLOR/NO_COLOR in GitLab CI, just raw command run:

```
script:
  - lychee2 .
```

What I did wrong in my CI, or what info from me required?

**Comment by mre** [comment] 2024-04-15 16:22
I think the issue is on my end. Need to make more changes in the pull request. Apologies for the noise.

**Comment by adoyle-h** [comment] 2024-09-01 11:45
I think it should be always trim colors for output file. `NO_COLOR=1` is a redundant option. Who need the terminal color codes included in file?

**Comment by alexanderbazhenoff** [comment] 2024-09-04 17:52
> I think it should be always trim colors for output file. `NO_COLOR=1` is a redundant option. Who need the terminal color codes included in file?

In this way `COLORS=1` will be apprectiated :)
In practice, colors/emojis have become more readable in GitLab or other CI platforms output. Not everyone wants to aggregate CI logs outside of GitLab, but b/w as defaults is also ok.

**Comment by mre** [comment] 2024-10-08 22:56
With https://github.com/lycheeverse/lychee/pull/1398 being merged, I think we can close this.

To recap, the main request for a raw output option has been implemented with `--format=raw --no-progress`.

There's an ongoing discussion about color output in CI environments, particularly GitLab CI:
The `NO_COLOR` environment variable doesn't seem to be working as expected over there?
Maybe it's already been resolved by now, either on the GitLab side or on lychee's side after merging #1398? 
Either way, if someone finds the time, please investigate why `NO_COLOR` isn't working as expected in GitLab CI and create a new issue if needed.

**Closed by mre** 2024-10-08 22:56 UTC
Labels: enhancement, good first issue, help wanted

**Comment by mre** [comment] 2024-10-08 23:17
I've also documented the output modes [on the documentation website here](https://lychee.cli.rs/usage/output/)
