### ISSUE TITLE
Link, crossorigin, and integrity directive are being combined into unresolvable link

### ISSUE THREAD

**Issue by aj-stein-nist** [lycheeverse/lychee#1020] opened 2023-03-27 20:13 UTC
Hello, a colleague and I were testing `0.11.1` on some content and we see in our website builds through a Hugo template  a `<script/>` tag is created that looks like this.

```sh
cat about/index.html
<html>
<head>Test</head>
<script src=https://cdnjs.cloudflare.com/ajax/libs/tocbot/4.12.0/tocbot.min.js integrity=sha384-roIHE2HuL+PZHzo8X7MgpHu256WMUJvsKqI2GaUJY3moVp06oLtx0QvZnvZJdcCb crossorigin=anonymous referrerpolicy=no-referrer></script>
<script type=text/javascript src=../js/site.min.js integrity="sha512-TOjPncw6vJGMqCN0T2rsjrQya/QLKFveYQcF5PwoN6zXlxEROomkD0l86oPwX7qmDrA4M5K5+OZOA6vCIY4lQA=="></script>
<script type=text/javascript src=https://pages.nist.gov/leaveNotice/js/jquery.leaveNotice-nist.min.js></script>
<script>$(document).ready(function(){$('a[href*="//"]:not([href*="pages.nist.gov"]):not([href*="www.nist.gov"]):not([href^="#"]):not([href^="/"])').addClass("usa-link usa-link--external"),$("a.usa-link--external").leaveNotice()})</script><script src=https://cdnjs.cloudflare.com/ajax/libs/anchor-js/4.3.0/anchor.min.js integrity="sha512-G2OGlm41XXw+fcgDcRPjVYEn7qCY6qiKWNqDGT37SnKh0qtRXTuKZ5/UQR0kDN0PZRNWcGExd3lAeqEH0I36bQ==" crossorigin=anonymous></script>
<script>anchors.options={placement:"left"},anchors.add()</script><script>tocbot.init({tocSelector:"#js-toc",contentSelector:"#main-content",headingSelector:"h2,h3,h4",includeHtml:!1,collapseDepth:0,hasInnerContainers:!0,orderedList:!1,listClass:"usa-sidenav",extraLinkClasses:"usa-sidenav__item",activeLinkClass:"usa-current",headingsOffset:1,scrollSmoothOffset:0})</script>
</body>
</html>
```

The end result is it always returns a HTTP 403 or 404 response code. It appears to be munging everything together from various script tags and their attributes.

```sh
$ lychee --no-progress --verbose --accept 200,206,429 'about/index.html' --exclude-mail --format json
{
  "detailed_stats": true,
  "total": 1,
  "successful": 0,
  "unknown": 0,
  "unsupported": 0,
  "timeouts": 0,
  "redirects": 0,
  "excludes": 0,
  "errors": 1,
  "cached": 0,
  "success_map": {},
  "fail_map": {
    "about/index.html": [
      {
        "url": "https://cdnjs.cloudflare.com/ajax/libs/tocbot/4.12.0/tocbot.min.jssha384-roIHE2HuL+PZHzo8X7MgpHu256WMUJvsKqI2GaUJY3moVp06oLtx0QvZnvZJdcCbanonymousno-referrertext/javascript../js/site.min.jssha512-TOjPncw6vJGMqCN0T2rsjrQya/QLKFveYQcF5PwoN6zXlxEROomkD0l86oPwX7qmDrA4M5K5+OZOA6vCIY4lQA==text/javascripthttps://pages.nist.gov/leaveNotice/js/jquery.leaveNotice-nist.min.jshttps://cdnjs.cloudflare.com/ajax/libs/anchor-js/4.3.0/anchor.min.jssha512-G2OGlm41XXw+fcgDcRPjVYEn7qCY6qiKWNqDGT37SnKh0qtRXTuKZ5/UQR0kDN0PZRNWcGExd3lAeqEH0I36bQ==anonymous",
        "status": "Failed: Network error"
      }
    ]
  },
  "excluded_map": {}
}
```
I saw some similar issues in the backlog and I am confused as to whether this needs to be reported to the linkify project. I either might be unable to reproduce it or I misunderstand its output.

![image](https://user-images.githubusercontent.com/94922603/228055700-d7c9a32b-9ae2-402c-9b8a-efc1e17ff099.png)

When I try the content of this webpage in the test interface, it seems to highlight the links properly, suggesting it does not combine them all together as a target link to check. Can you help me reproduce this more easily for you to confirm if this is a bug in lychee, a bug in linkify, intended behavior for one of them, or intended behavior of both.

**Comment by mre** [comment] 2023-03-27 20:36
Yeah can you check to build lychee from latest `master` and test again. I guess we fixed that lately.

**Comment by mre** [comment] 2023-03-27 22:03
`<script>` tags are excluded by default, as they usually contain non-user-facing URLs. To include them, use `--include-verbatim`.

Try

```bash
cargo run -- --dump --include-verbatim about/index.html
```

and

```bash
cargo run -- --include-verbatim about/index.html
```

**Comment by aj-stein-nist** [comment] 2023-03-27 23:22
So this was/is a recent regression that was fixed? We are seeing it does detect the embedded links in the script tag when using the current release. We are using the action your org provides in a worfklow, with `0.11.1` and a colleague reported the same behavior when testing locally, so I tried this. With `0.11.1` it does seem to pick up these links and report errors, with several combined and the relevant attributes included. You are right, it does report them and give relevant errors when using the commands above, but we are not using that.

We are doing this in the workflow config and locally with `0.11.1` and older:

```sh
lychee --exclude-path path/to/.lycheeignore --no-progress --verbose --accept 200,206,429 '**/*.html' --exclude-mail
```

For this report all I did was make the smallest repro possible. If I understand correctly and it was fixed, we have to wait for a new release or build ourselves to use in the action with a custom override, correct?

**Comment by mre** [comment] 2023-03-27 23:27
> So this was/is a recent regression that was fixed?

Yes.

>  If I understand correctly and it was fixed, we have to wait for a new release or build ourselves to use in the action with a custom override, correct?

Yes, exactly.

The new release will land soon. Not sure if I'll wait for #535. If it's a priority for your team, I can try to prioritize the release.

**Comment by aj-stein-nist** [comment] 2023-03-28 12:36
> The new release will land soon. Not sure if I'll wait for #535. If it's a priority for your team, I can try to prioritize the release.

I defer to @david-waltermire-nist on that one. Strangely it has not caused errors for me yet, but will eventually for reasons specific to our project and branch management. I will let him chime in if he feels strongly.

**Comment by david-waltermire-nist** [comment] 2023-03-28 13:29
@mre Thank you so much for weighing in on this. If the release is in the next couple weeks, we can wait. Thanks again for the quick response!

**Comment by mre** [comment] 2023-03-28 14:39
Oh yes, of course. I'm hoping that we can do a new release soon if time permits.

**Comment by mre** [comment] 2023-04-11 23:03
Closing this as the issue is resolved. Release coming up very soon.

**Closed** 2023-04-11 23:02 UTC
