### ISSUE TITLE
Invalid fragments are ignored silently

### ISSUE THREAD

**Issue by laralove143** [lycheeverse/lychee#743] opened 2022-08-19 18:40 UTC
A link like `https://github.com/lycheeverse/lychee#installationn` passes as OK even though the fragment is invalid and using the link just goes to the top page, which is very undesirable for long pages or static sites

**Comment by lebensterben** [comment] 2022-08-19 19:04
it's Ok in the sense that the server returns okay response.

fragment resolution entirely depends on the client. to implement this we need to find an html element with matching id or name.

**Comment by mre** [comment] 2022-09-21 00:09
Yeah fragment resolution is not supported yet. We'd need a "fragment cache" or something to look up fragments as we go. This is a duplicate of https://github.com/lycheeverse/lychee/issues/185.
@laralove143 if you want to take a look I'd be thankful. We should come up with a design proposal over there; maybe you can help.
Closing this to focus discussion on the older issue. 😉

**Closed by mre** 2022-09-21 00:09 UTC
