### ISSUE TITLE
Confusing exit 2, although no error visible

### ISSUE THREAD

**Issue by guettli** [lycheeverse/lychee#1477] opened 2024-08-06 09:36 UTC
We get exit status `2`, although no error is visible:

```
lychee --config .lychee.toml ./*.md  ./docs/**/*.md
  110/110 ━━━━━━━━━━━━━━━━━━━━ Finished extracting links
🔍 110 Total (in 9s) ✅ 96 OK 🚫 0 Errors 💤 13 Excluded

Exit 2
```

Version: 0.15.1

If you look carefully: 96+13 = 109, but 110 were processed.

With `--verbose` I found the issue:

```
? [999] https://www.linkedin.com/company/example.com/ | Unknown status (999 <unknown status code>)
```

Please provide a better error message in the future. It took us some time to find the root cause.

Nevertheless, thank you very much for Lychee!

**Comment by thomas-zahner** [comment] 2024-08-28 18:44
Thanks for reporting. The result lychee outputs by default if non-standard status codes are encountered may indeed be counterintuitive. If you use a different format (`--format`) it gets clearer as it shows up as `unknown`:

`$ echo "https://httpstat.us/999" | lychee --format detailed -`

```
📝 Summary
---------------------
🔍 Total............1
✅ Successful.......0
⏳ Timeouts.........0
🔀 Redirected.......0
👻 Excluded.........0
❓ Unknown..........1
🚫 Errors...........0
```

`999` is not an accepted status code by default, but you could change that with `--accept 999`
So as explained in the README.md the exit code is correct behaviour:

> `2` for link check failures (if any non-excluded link failed the check).

So this is not a bug. But I think what we could do is to show `Unknown` (and same with `Timeouts`?) when `--format` is `compact` and the count is not zero. What do you think @mre?

**Comment by mre** [comment] 2024-08-28 22:41
Yup, good idea. We could change that. 👍

**Comment by mre** [comment] 2024-08-28 22:42
If you find the time, feel free to create a PR for that. Happy to get it merged.

**Comment by mre** [comment] 2024-09-09 16:35
@thomas-zahner fixed it in `master`. @guettli, in case you want to try, please check out lychee from the sources or wait until the next release.

**Comment by guettli** [comment] 2024-09-09 18:30
@mre thank you very much. It is hard to reproduce, we get the useless http status code 999 only sometimes. I trust you. Thank you!

**Closed** 2024-09-27 21:35 UTC

**Comment by mre** [comment] 2024-10-07 10:41
This is now part of the latest release, 0.16.1.
