### ISSUE TITLE
Unrecognised escape sequence (\/)

### ISSUE THREAD

**Issue by wolf99** [lycheeverse/lychee#663] opened 2022-06-25 18:13 UTC
I am trying to add a `.lycheeignore` file that will ignore `https://www.godaddy.com/`. (Because it returns infinite HTTP 302s as it tries to redirect to a localized page).

I'd like to be able to ignore even if the trailing sforward slash is present or not.
So I construct the following regex:

```regex
godaddy\.com(\/)?$
```

https://github.com/GitCredentialManager/git-credential-manager/pull/700/commits/e848ba83d5fcedd4f716573b1e350a87d304dd5e

However, lychee appears to barf on this regex:

```console
+ eval lychee --format markdown --output /tmp/lychee/out.md --user-agent '"Mozilla/5.0' '(Windows' NT '10.0;' 'Win64;' 'x64)' AppleWebKit/[53](https://github.com/GitCredentialManager/git-credential-manager/runs/7055448925?check_suite_focus=true#step:3:56)7.36 '(KHTML,' like 'Gecko)' Chrome/100.0.4896.75 'Safari/537.36"' --no-progress .
++ lychee --format markdown --output /tmp/lychee/out.md --user-agent 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/100.0.4896.75 Safari/537.36' --no-progress .
Error: regex parse error:
    godaddy\.com(\/)?$
                 ^^
error: unrecognized escape sequence
+ exit_code=1
```

I've stared at this for about 30 mins on regex101.com, but I cannot see how this is wrong regex.

See: https://regex101.com/r/P1B4wT/1

![image](https://user-images.githubusercontent.com/281700/175785478-b1bbee87-4963-4f13-82f9-403c411873e0.png)

I tried with a non-capturing group also, but no change: https://github.com/GitCredentialManager/git-credential-manager/pull/700/commits/bc76c6edae9eaa6990c802398e1a894aad03d3c3

**Comment by mre** [comment] 2022-06-26 13:57
Moved to the main lychee repo, because the error is reproducible without the action.

**Comment by mre** [comment] 2022-06-26 13:58
I'm gonna close this as resolved. Feel free to reopen in case it doesn't work. 😊

**Closed by mre** 2022-06-26 13:58 UTC

**Comment by wolf99** [comment] 2022-06-26 19:56
Not sure I grok the explanation, but it works 🤷 
Thanks!

**Comment by mre** [comment] 2022-06-26 20:47
Backslash is commonly associated with escaping the next character in a string, I thought it fails is because it should be escaped once for the string literal, and once for the regex as described [here](https://stackoverflow.com/questions/4025482/cant-escape-the-backslash-with-regex). 

However I think it's because `\/` is a no-op escape in the Rust regex crate. See the discussion [here](https://github.com/rust-lang/regex/issues/501).
That means you can also just use 

```
godaddy\.com/?$
```
