### ISSUE TITLE
Non existing github blob files are reported as 200

### ISSUE THREAD

**Issue by vcomito-apexai** [lycheeverse/lychee#449] opened 2022-01-09 22:44 UTC
It looks like lychee is reporting some github address with result HTTP OK 200, while they should be NOT FOUND 404

```console
$ cat example.md
[](https://github.com/lycheeverse/lychee/blob/master/README.md)

[](https://github.com/lycheeverse/lychee/blob/master/NON_EXISTENT_FILE.md)
```

```console
$ lychee example.md --github-token MY_GITHUB_TOKEN

🔍 2 Total ✅ 2 OK 🚫 0 Errors

$ lychee --version
lychee 0.8.1
```

```console
$ curl -I https://github.com/lycheeverse/lychee/blob/master/README.md 2>&1 | grep HTTP                                                                                           
HTTP/2 200 

$ curl -I https://github.com/lycheeverse/lychee/blob/master/NON_EXISTENT_FILE.md 2>&1 | grep HTTP 
HTTP/2 404 
```

**Comment by mre** [comment] 2022-01-10 00:08
Thanks for the report. This was fixed in `master` with https://github.com/lycheeverse/lychee/pull/445. There will be a new release soon. In the meantime you can try with `cargo install --git https://github.com/lycheeverse/lychee`.

**Comment by mre** [comment] 2022-01-10 00:45
Went ahead and published a new version (0.8.2).
Can you try again with [one of the binaries](https://github.com/lycheeverse/lychee/releases/tag/v0.8.2) or with `cargo install lychee`?

**Comment by vcomito-apexai** [comment] 2022-01-10 07:05
Thanks for the quick answer @mre 

Unfortunately, it looks like the same issue appears both on master and in released version `0.8.2`

```console
$ lychee --version
lychee 0.8.2
$ lychee example.md --github-token MY_GITHUB_TOKEN
🔍 2 Total ✅ 2 OK 🚫 0 Errors
```

**Comment by mre** [comment] 2022-01-10 11:09
Very strange. Does it work without the token? (It does for me.)

**Comment by vcomito-apexai** [comment] 2022-01-10 11:21
Here's the result without the token

```console
$ lychee example.md                                                        
Issues found in 1 input(s). Find details below.

[example.md]:
✗ https://github.com/lycheeverse/lychee/blob/master/NON_EXISTENT_FILE.md: GitHub token not specified. To check GitHub links reliably, use `--github-token` flag / `GITHUB_TOKEN` env var.

🔍 2 Total ✅ 1 OK 🚫 1 Error (HTTP:1)
```

I would say however that the error should be reported even when the token is available. 
Sorry but I could not look into lychee code myself, I may be able to do it next weekend.

**Comment by mre** [comment] 2022-01-10 17:14
> I would say however that the error should be reported even when the token is available.

Absolutely. The issue is certainly in the fallback for Github. 
Here's what we should do:

* Don't check files with the API, only repositories. That's a bug in lychee. 🐛 
* Add tests for the above. ✅ 

That said, I tried it yesterday and it worked for me (even with the token set), so I don't know what's going on.

**Comment by mre** [comment] 2022-01-10 21:15
See #384 for a possible fix. Does it work with that?

**Comment by mre** [comment] 2022-01-12 08:26
Should be fixed in `master` now. Please reopen if it's still not working. A new version will be published in the near future. 
Thanks for creating an issue. 👍

**Closed by mre** 2022-01-12 08:26 UTC
Labels: waiting-for-feedback
